Repository windup/windup_ide_tests, pull requests merged in 2024-03, with the labels that each got.

#123 [RFR] adjust Intellij file path
  src/fixtures/ide.py
  src/models/IDE/Intellij.py
  src/utils/general.py
Labels: infra, intellij

#124 Read the current object in the model json file
  src/models/configuration/configurations_object.py
Labels: RFR, vscode

#126 added the list of targets and sources
  src/data/kantra_sources_targets_list.json
Labels: infra
